[package]
description = "Common testing helpers for Injective Test Tube"
edition     = "2021"
license     = "Apache-2.0"
name        = "testenv"
version     = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
cosmwasm-std        = { workspace = true }
cw-storage-plus     = { workspace = true }
enumset             = { workspace = true }
injective-cosmwasm  = { workspace = true }
injective-math      = { workspace = true }
injective-std       = { workspace = true }
injective-test-tube = { workspace = true }
injective-testing   = { workspace = true }
prost               = { workspace = true }
schemars            = { workspace = true }
serde               = { workspace = true }
serde-cw-value      = { workspace = true }
serde-json-wasm     = { workspace = true }
thiserror           = { workspace = true }
